---

- name: Start
  hosts: localhost
  remote_user: testuser1
  gather_facts: false
  vars_files:
    - /Users/lacarter/Documents/Pluralsite_Training/Ansible/aws_ansible/vars/info.yml

  tasks:
    - name: create a VPC with default tenancy
      ec2_vpc_net:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: test_vpc_net
        cidr_block: 10.10.0.0/16
        tags:
          module: ec2_vpc_net
        tenancy: default
      register: ansibleVPC

    - name: vpc output
      debug:
        var: ansibleVPC

    - name: create VPC Internet Gateway
      ec2_vpc_igw:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        state: present 
        tags: 
          Name: ansibleIGW
      register: ansibleIGW

    - name: igw output
      debug:
        var: ansibleIGW

    - name: create VPC Internet Gateway
      ec2_vpc_igw:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        vpc_id: "{{ ansibleVPC.vpc.id }}"
        state: present
        cidr: 
        tags: 
          Name: Database_Subnet
      register: database_subnet