---

- name: Start
  hosts: localhost
  remote_user: testuser1
  gather_facts: false
  vars_files:
    - /Users/lacarter/Documents/Pluralsite_Training/Ansible/aws_ansible/vars/info.yml

  tasks:
    - name: create VPC Internet Gateway
      ec2_vpc_igw:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        vpc_id: vpc-0d566902260a2d18b
        state: present 
      register: ansibleIGW

    - name: igw output
      debug:
        var: ansibleIGW