---

- name: Start
  hosts: localhost
  remote_user: testuser1
  gather_facts: false
  vars_files:
    - /Users/lacarter/Documents/Pluralsite_Training/Ansible/aws_ansible/vars/info.yml

  tasks:
    - name: create a VPC with default tenancy
      ec2_vpc_net:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        name: test_vpc_net
        cidr_block: 10.10.0.0/16
        tags:
          module: ec2_vpc_net
        tenancy: default
      register: ansibleVPC

    - name: vpc output
      debug:
        var: ansibleVPC